### ISSUE TITLE
[Feature Request] Add light block support to furniture

### ISSUE THREAD

**Issue by paulreob** [Xiao-MoMi/craft-engine#136]
Example config:
```yaml
lights:
  - position: 0,0,0
    width: 1
    height: 1
    level: 15
  - position: 0,1,0
    width: 1
    height: 1
    level: 13
```

![Image](https://github.com/user-attachments/assets/294058b2-6acc-493a-b26b-fab498270d32)
